apiVersion: v1
description: "Transformation service: to compute on-demand features"
name: transformation-service
version: 0.19.4
appVersion: v0.19.4
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast